server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://192.168.1.151:3306/user_center?nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: Citi2013
      driver-class-name: com.mysql.cj.jdbc.Driver


