server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://192.168.1.151:3306/content_center?nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: Citi2013
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  application:
    name: content-center


