server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://192.168.1.151:3306/content_center?nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: Citi2013
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
    sentinel:
      transport:
      # 指定sentinel控制台地址
        dashboard: localhost:8080


  application:
    name: content-center
  # Feign get request
  main:
    allow-bean-definition-overriding: true
ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    # 打印Feign日志
    com.sonic.contentcenter.feignclient.UserCenterFeignClient: debug

feign:
  client:
    config:
#    想要调用的微服务名称
#      user-center:
# 全局属性配置
      default:
        loggerLevel: full
  httpclient:
  # 让feign使用apache httpclient做请求，而不是默认的urlconnnection
    enabled: true
    # feign最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
management:
  endpoints:
    web:
      exposure:
        include: "*"


#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


