server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://192.168.1.151:3306/content_center?nullCatalogMeansCurrent=true
    hikari:
      username: root
      password: Citi2013
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ

  application:
    name: content-center
ribbon:
  eager-load:
    enabled: true
    clients: user-center
logging:
  level:
    # 打印Feign日志
    com.sonic.contentcenter.feignclient.UserCenterFeignClient: debug

#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


