#Spring boot \u4F4D\u7F6E\u6587\u4EF6
#server.port=8081
#management.endpoint.health.show-details=${var_env}
#management.endpoints.web.exposure.include=metrics,health,info


# Mybatis
mybatis:
  mysql1:
    userName: root
    password: Citi2013
    url: jdbc:mysql://192.168.1.151:3306/mybatis?useSSL=false&allowMultiQueries=true
    driverClassName: com.mysql.cj.jdbc.Driver
    mapperLocationList:
      - classpath*:/mybatis/mapper/mysql1/*.xml

logging:
  level:
    com.**.**.**.mapper: debug