# DataSource
datasource:
  primary:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.1.151:3306/mybatis?useSSL=false&allowMultiQueries=true
    username: root
    password: Citi2013

# Mybatis
mybatis:
  mapperLocationList:
    - classpath*:/mybatis/mapper/*.xml
  type-handlers-package: com.sonic.handler

# Log
logging:
  level:
   com.sonic.mapper: debug

# Spring
spring:
  aop:
    proxy-target-class: false

# management
management:
  endpoints:
    web:
      exposure:
        include: '*'

