# DataSource
datasource:
  primary:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.1.151:3306/mybatis?useSSL=false&allowMultiQueries=true
    username: root
    password: Citi2013

# 如果要只用Java动态代理，必须设置为false，默认设置见：spring-boot-autoconfigure-2.1.0.RELEASE.jar/META-INF/spring-configuration-metadata.json
spring:
  aop:
    proxy-target-class: false

# Mybatis
mybatis:
  mapperLocationList:
    - classpath*:/mybatis/mapper/*.xml
logging:
  level:
   com.sonic: debug

