# DataSource
datasource:
  primary:
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.1.151:3306/mybatis?useSSL=false
    username: root
    password: Citi2013


# Mybatis
mybatis:
  mapperLocationList:
    - classpath*:/mybatis/mapper/*.xml
logging:
  level:
   com.sonic.mapper: debug

